<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Middleware\RoleMiddleware;
use Spatie\Permission\Middleware\PermissionMiddleware;
use Spatie\Permission\Middleware\RoleOrPermissionMiddleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        api: __DIR__.'/../routes/api.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
        then: function () {
            // Interactive Swagger UI for the whole API. Gated to non-production so
            // the full API surface isn't advertised publicly in prod. The OpenAPI
            // spec is generated by Scribe (`php artisan scribe:generate`).
            if (! app()->environment('production')) {
                Route::get('/swagger', function () {
                    return view('swagger', ['specUrl' => route('scribe.openapi')]);
                })->name('swagger');

                // The app root has no page of its own (this is an API backend), so
                // send visitors to the API docs instead of a bare 404.
                Route::get('/', fn () => redirect()->route('swagger'));
            }
        },
    )
    ->withMiddleware(function (Middleware $middleware) {
         $middleware->alias([
            'role' => RoleMiddleware::class,
            'permission' => PermissionMiddleware::class,
            'role_or_permission' => RoleOrPermissionMiddleware::class,
            'verified' => \App\Http\Middleware\EnsureEmployerIsVerified::class,
        ]);

        // Defensive HTTP headers on every response (clickjacking, MIME sniffing, …).
        $middleware->append(\App\Http\Middleware\SecurityHeaders::class);

        // Drive scheduled email campaigns from normal API traffic (terminable,
        // throttled to once/min) so they send automatically without a system
        // cron. See App\Http\Middleware\TriggerDueCampaigns.
        $middleware->api(append: [
            \App\Http\Middleware\TriggerDueCampaigns::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
